version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: licenta-postgres
    environment:
      POSTGRES_DB: licenta_db
      POSTGRES_USER: licenta_user
      POSTGRES_PASSWORD: licenta_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: